import { ResponsiveModal } from "@/components/responsive-modal";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/trpc/client";
import { Bot, Flag, MessageSquareWarning, Sparkles, ThumbsDown } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

interface VideoReportModalProps {
    videoId: string;
    open: boolean;
    onOpenChange: (open: boolean) => void;
}

const REPORT_REASONS = [
    {
        id: "ai",
        label: "AI-generated content",
        description: "Content that appears to be generated by AI without disclosure",
        icon: Sparkles
    },
    {
        id: "clickbait",
        label: "Clickbait or Misleading",
        description: "Title or thumbnail is misleading",
        icon: ThumbsDown
    },
    {
        id: "inappropriate",
        label: "Inappropriate content",
        description: "Content that violates community guidelines",
        icon: Flag
    },
    {
        id: "spam",
        label: "Spam or Scam",
        description: "Misleading or repetitive content",
        icon: MessageSquareWarning
    },
    {
        id: "harassment",
        label: "Harassment or Bullying",
        description: "Content that harasses or bullies individuals",
        icon: Bot
    }
];

export const VideoReportModal = ({
    videoId,
    open,
    onOpenChange
}: VideoReportModalProps) => {
    const [selectedReason, setSelectedReason] = useState<string | null>(null);
    const [details, setDetails] = useState("");

    const utils = trpc.useUtils();
    const createReport = trpc.reports.create.useMutation({
        onSuccess: () => {
            toast.success("Report submitted successfully");
            utils.reports.getPolls.invalidate({ videoId });
            onOpenChange(false);
            setSelectedReason(null);
            setDetails("");
        },
        onError: (err) => {
            toast.error(err.message);
        }
    });

    const handleSubmit = () => {
        if (!selectedReason) return;

        createReport.mutate({
            videoId,
            reason: selectedReason as any,
            details
        });
    };

    return (
        <ResponsiveModal
            title="Report Video"
            open={open}
            onOpenChange={onOpenChange}
        >
            <div className="flex flex-col gap-4 p-4">
                <p className="text-sm text-muted-foreground">
                    Please select a reason for reporting this video.
                </p>
                
                <div className="flex flex-col gap-2">
                    {REPORT_REASONS.map((reason) => (
                        <div
                            key={reason.id}
                            className={`
                                flex items-start gap-3 p-3 rounded-lg border cursor-pointer transition-colors
                                ${selectedReason === reason.id 
                                    ? "bg-accent border-primary" 
                                    : "hover:bg-accent/50 border-transparent bg-secondary/20"
                                }
                            `}
                            onClick={() => setSelectedReason(reason.id)}
                        >
                            <reason.icon className="size-5 mt-0.5 text-muted-foreground" />
                            <div className="flex flex-col">
                                <span className="font-medium text-sm">{reason.label}</span>
                                <span className="text-xs text-muted-foreground">{reason.description}</span>
                            </div>
                        </div>
                    ))}
                </div>

                {selectedReason && (
                    <div className="flex flex-col gap-2 animate-in fade-in slide-in-from-bottom-2">
                        <label className="text-sm font-medium">Additional Details (Optional)</label>
                        <Textarea 
                            placeholder="Provide more context..." 
                            value={details}
                            onChange={(e) => setDetails(e.target.value)}
                            className="resize-none"
                        />
                    </div>
                )}

                <div className="flex justify-end gap-2 mt-2">
                    <Button variant="ghost" onClick={() => onOpenChange(false)}>
                        Cancel
                    </Button>
                    <Button 
                        onClick={handleSubmit} 
                        disabled={!selectedReason || createReport.isPending}
                    >
                        {createReport.isPending ? "Submitting..." : "Submit Report"}
                    </Button>
                </div>
            </div>
        </ResponsiveModal>
    );
};
